### ISSUE TITLE
cant download

### ISSUE THREAD

**Issue by Thunderstarr** [MCJack123/DashBot-3.0#1]
Tried downloading dashbot.exe from multiple web browsers and they all remove it for detecting a virus. Could you fix this?

**Comment by MCJack123** [comment]
Unfortunately, this is an issue that I cannot fix because the program uses functions to read memory from other processes, which is something that some anti-virus software checks for. This is a false positive, but if you don't trust it you can compile it yourself.

If the file was quarantined by Windows ~~Defender~~ Security Essentials, you can restore the file using the instructions in this article: https://www.ghacks.net/2017/11/23/how-to-handle-failed-downloads-virus-detected-issues-on-windows-10/

**Comment by Thunderstarr** [comment]
It is not my anti-virus, it is the browser itself. What do you suggest downloading it from?
